addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  matrix:
    secure: o4XYTxvP18fsWYTuDO3Px6bof5mkQCn8fYc7FG7MjRG29nLgNVvjzx/R2oW5Hh02+ZZTAZQOHc5MFJdHO5j7S/rGplJTpCBb19wn4SGB8o41hlGpUCOe4sKEbk/3+9Ii4e9EmschmkZgvmBxJLTVtqnM7J0IB6ny1D/IN/M67/TAxSPB9GCdwJRc+1LzGXB/OhJLW/LmdekEnAg06zYcDC0o+Uf7t0l62dawWHkfgrgYGIR+JblJLb9iaxWGTrt7HoUhTCot5YWEkPj8uT2/u/cg2oLsXDcPSK2xmc6J+bX1qMMv1bIPhlHsmitxKHL8Im0wQkfcLeHKSZtqAAyZ5dhy3djKCJJ2gJ4fhAhDLpnslSrbJpuBxpljLR0zuDu0INrwMhIPm30DNwfRj8G/OA83EPqBYGDH5eEsfv4iKipbrAR9oIw607SkHoQqXuvHwzrJy7kYacM3N4yxmNRiXKgtVZd5E6cNVt+zSoj3oQeqVYHVEeExXtdRMvMSMDvVRX/PMgVArFaVVVaLOqbNmtcWLxZBPDC3zwt5y+ChvcG3gEkc/wpYC1BfwSQjvV+acg6UM7XJDe0ximCV3wxWjGB1rAdsWfhkozc+1WhS3ByhZryvdr1QhQYIUsAJI2hsB3aeNYx9EtsfSIccpzwLs9hpfbS6vSLnHIjKDB3yP+E=
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
before_install:
- gem install bundler -v 1.16.6
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1
language: ruby
cache: bundler
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
